server:
  port: 8999
  
eureka:
  instance:
    a-s-g-name: localhost
  
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/Customer/**
      - id: contact-service
        uri: lb://contact-service
        predicates:
        - Path=/Contact/**
